### ISSUE TITLE
Small issues when spectating a player

### ISSUE THREAD

**Issue by Zoiter7** [stefvanschie/buildinggame#79] opened 2017-07-31 22:39 UTC
When you enter like spectator, the other player can't place a blocks where you are and you don't see the chat but you can send messages.

And the spectators can vote using the command /bg vote

You can change the gamemode 1 to gamemode 3 when is spectating.

==========================
OTHER ISSUES
When you normally using the command /bg vote, in the console gives this error, but the command works.  https://hastebin.com/mowaganele.vbs

When you use the redstone for leave of arena, seems if you use the redstone cliking to floor, gives this error in console. https://hastebin.com/lusaqipipe.vbs

**Comment by stefvanschie** [comment] 2017-08-01 09:27
Verified, working on the issues.

For your last issue however (with the redstone item), could you show me your config.yml (or at least the part that contains the item information)?

**Comment by Zoiter7** [comment] 2017-08-01 14:44
I don't change the item never, is of default config.

`leave-item:
  slot: 8
  id: redstone`

**Comment by stefvanschie** [comment] 2017-08-02 15:33
I've reproduced the error (with the leave item) and submitted a bug report to Spigot. I'm uncertain if they will fix it however as it is partially caused by my plugin caused by my plugin (even though the stack trace doesn't mention it). Hopefully they will fix it otherwise I'll have to do it, which would include delaying the code with ~0.05 seconds.

In case you're interested, here is the link to the report: https://hub.spigotmc.org/jira/browse/SPIGOT-3486

I'm still working on the other issues, ~66% done with those.

**Comment by Zoiter7** [comment] 2017-08-07 13:24
Seems md_5 resolved the case =p

I found a small bug, when you are in team mode, the lore of the teams doesn't update, only shows the lore of the Team 1, but if you move of the team 1 to another team also  the lore doesn't update.

**Comment by stefvanschie** [comment] 2017-08-07 16:07
The players will spawn at a position that doesn't have any blocks so they don't get stuck. If the top-corner doesn't have any blocks that means they'll spawn there.

Verified the other bugs you mentioned.

**Comment by stefvanschie** [comment] 2017-09-01 15:39
Issues have been fixed in version 5.0.4

**Closed by stefvanschie** 2017-09-01 15:39 UTC
